### PR TITLE
Do not cache reading the HEAD commit

### LINKED ISSUE #1368: gs_show_commit with `HEAD` opens up the wrong commit
It used to show the last commit in current branch (i.e HEAD), and now it seems stuck to some commit down the tree... perhaps there's some caching magic that was added that identifies HEAD as a unique commit :/ .. not sure if there's a use case here for typical GitSavvy usage; but, for me, it can be nice to see a `skip_cache` sort of argument to avoid this.

### PR DESCRIPTION
**Pull request by kaste**
Fixes #1368

Do not cache reading the HEAD commit. Everywhere else, we already checked if the `commit_hash` is `""` or `"HEAD"` to skip caching, so this one was missing here.

We go one step further, special case "HEAD", and dynamically update and thus follow HEAD.

The use case is a user binding to `gs_show_commit` with `commit_hash`
set to `HEAD`.  For example:

```
  {
      "caption": "git: show HEAD commit",
      "command": "gs_show_commit",
      "args": {
          "commit_hash": "HEAD"
      }
  },
```

However, arbitrary references, like for example tags or branch names, are not supported.

### CODE REVIEW

**Comment by asfaltboy** [comment]
Looking good, fix works except it doesn't refresh an existing open "show commit view"

**Comment by kaste** [comment]
Yeah, I noticed that we actually fall down the rabbit hole rather immediately.  ("some" features fail, LOL)

a) We resolve HEAD to a commit hash; then everything works, and usually every time you invoke the command a new view gets created *except* HEAD didn't move.  (After your commit it *always* creates a new view.)  (Resolving would mean **1** extra git call for that special case.)

b) We just refresh, basically like all other views, for example `on_activated`, if and only if the commit is HEAD of course.  (For all other views the content is cacheable and static.)  Then we had a changing view for the HEAD case, basically if you don't close it, it would follow the current branch. 

🤔

**Review by asfaltboy — APPROVED** [review]
I'm not sure I understand how the listener works, but I tested it and it worked fine for me 👍

**Comment by kaste** [comment]
I reverted the dynamic "follow HEAD" approach and just resolve "HEAD". T.i. I implemented a) from above comment. 

I don't feel that "Show commit" should be *not* immutable right now.  If we have previous/next commit navigation here, this feeling might change.

**Pull request merged**
