### PR TITLE
missing force argument

### PR DESCRIPTION
**Pull request by randy3k**
The `force` argument was missing.

### CODE REVIEW

**Comment by kaste** [comment]
Yeah, fair. At least it asked you to delete anyway.  (I probably wanted to deprecate the `D` binding. But since then I always delete branches in the graph view.)

**Comment by randy3k** [comment]
How did you delete a branch in graph view? I can't find such an option.

**Comment by kaste** [comment]
`[enter]`

image

**Comment by randy3k** [comment]
Oh, I must be blinded... 🤦

**Pull request merged**
